; ---------------------------------------------------------------------------
; MI library routines

mi_main                                 := $7400

mi_race_name_table                      := $7763;
mi_attribute_table                      := $7842;
mi_class_name_table                     := $7911;
mi_transport_table                      := $7930;
mi_string_table                         := $7A7F;

mi_current_attribute                    := $81C4;
mi_command_table_override               := $81C7;
mi_command_table_override_hi            := $81C8;

mi_player_save_data                     := $81E2;

mi_player_sound_flag                    := $81E7;
mi_player_position_x                    := $81E8;
mi_player_position_y                    := $81E9;
mi_player_equipped_spell                := $81EE;
mi_player_equipped_weapon               := $81EF;
mi_player_equipped_armor                := $81F0;
mi_player_current_vehicle               := $81F1;
mi_player_inventory_weapons             := $81F8;
mi_player_inventory_vehicles            := $8213;
mi_player_sex                           := $822C;
mi_player_name                          := $822D;
mi_player_hits                          := $823B;
mi_player_hits_hi                       := $823C;
mi_player_strength                      := $823D;
mi_player_agility                       := $823F;
mi_player_stamina                       := $8241;
mi_player_charisma                      := $8243;
mi_player_wisdom                        := $8245;
mi_player_intelligence                  := $8247;
mi_player_money                         := $8249;
mi_player_money_hi                      := $824A;
mi_player_race                          := $824B;
mi_player_class                         := $824D;
mi_player_food                          := $825A;
mi_player_food_hi                       := $825B;
mi_player_experience                    := $825C;
mi_player_experience_hi                 := $825D;
mi_player_random_seed                   := $8264;
mi_player_8267                          := $8267;
mi_player_826b                          := $826B;
mi_player_830c                          := $830C;

mi_number_padding                       := $85BE;

mi_print_char                           := $83D7;
mi_print_crlf_col_1                     := $83F3;
mi_cursor_to_col_1                      := $83F6;
mi_cursor_to_col_0                      := $8411;
mi_print_string_entry_x                 := $8426;
mi_print_string_entry_x2                := $842D;
mi_print_text_at_x_y                    := $848A;
mi_print_text                           := $848E;
mi_print_x_chars                        := $84B9;
mi_s84C0                                := $84C0;
mi_print_short_int                      := $8582;
mi_decode_and_print_command_a           := $85FD;
mi_s8689                                := $8689;
mi_update_stats                         := $86C6;
mi_restore_text_area                    := $8701;
mi_store_text_area                      := $870C;
mi_cmd_invalid                          := $876A;
mi_play_error_sound_and_reset_buffers   := $8772;
mi_reset_buffers                        := $8777;
mi_cmd_ztats                            := $890C;
mi_print_player_name                    := $8BA1;
mi_cmd_noise                            := $8BB9;
mi_player_died                          := $8BCE;
mi_load_ou_module                       := $8C5E;

mi_r77EC                                := $77EC;
mi_j863A                                := $863A;
mi_s863C                                := $863C;
mi_s8678                                := $8678;
mi_j8774                                := $8774;
