; ---------------------------------------------------------------------------
; ST library routines

CUR_X_OFF                           := $2E;
CUR_X_MAX                           := $2F;

CUR_Y_MIN                           := $30;
CUR_Y_MAX                           := $31;
CUR_X                               := $32;
CUR_Y                               := $33;

BM_ADDR_MASK                        := $5C;
BM2_ADDR_MASK                       := $5D;

st_sound_enabled_flag               := $1638;

st_w1632                            := $1632;
st_w1637                            := $1637;

st_init_snd_gfx                     := $163A;
st_do_nothing                       := $163D;
st_do_nothing2                      := $1640;
st_do_nothing3                      := $1643;
st_copy_screen_2_to_1               := $1646;
st_scroll_text_area_up              := $1649;
st_clear_current_text_row           := $164C;
st_clear_to_end_of_text_row_a       := $164F;
st_clear_text_window                := $1652;
st_set_text_window_full             := $1655;
st_set_text_window_stats            := $1658;
st_set_text_window_command          := $165B;
st_set_text_window_main             := $165E;
st_clear_main_viewport              := $1661;
st_swap_bitmaps                     := $1664;
st_print_char                       := $1667;
st_draw_world                       := $166A;
st_wait_for_input                   := $166D;
st_get_random_number                := $1670;
st_scan_and_buffer_input            := $1673;
st_read_input                       := $1676;
st_get_input                        := $1679;
st_draw_world_and_get_input         := $167C;
st_update_cursor                    := $167F;
st_play_sound_a                     := $1682;
st_queue_sound                      := $1685;
st_play_next_sound                  := $1688;

st_s168B                            := $168B;
st_s168E                            := $168E;
st_s1691                            := $1691;
st_s1694                            := $1694;

st_do_nothing4                      := $1697;
st_do_nothing5                      := $169A;
st_wait_for_raster                  := $169D;
st_delay_a_squared                  := $16A0;

