; ---------------------------------------------------------------------------
; MI library routines

race_name_table             := $7763;
r7842_table                 := $7842;
class_name_table            := $7911;

w81C4                       := $81C4;

player_save_data            := $81E2;

player_sound_flag           := $81E7;

player_sex                  := $822C;
player_name                 := $822D;
player_hits                 := $823B;
player_strength             := $823D;
player_agility              := $823F;
player_stamina              := $8241;
player_charisma             := $8243;
player_wisdom               := $8245;
player_intelligence         := $8247;
player_money                := $8249;
player_race                 := $824B;
player_class                := $824D;

player_food                 := $825A;
player_experience           := $825C;

w8264                       := $8264;
w8265                       := $8265;

w85BE                       := $85BE;

mi_print_char               := $83D7;
mi_s83F3                    := $83F3;
mi_cursor_to_col_1          := $83F6;
mi_cursor_to_col_0          := $8411;
mi_print_string_entry_x     := $8426
mi_print_text_at_x_y        := $848A;
mi_print_text               := $848E;
mi_print_x_chars            := $84B9;
mi_s84C0                    := $84C0;
mi_s8582                    := $8582;
mi_s8689                    := $8689;
mi_restore_text_area        := $8701;
mi_store_text_area          := $870C;
mi_s8772                    := $8772;
mi_s8BA1                    := $8BA1;

j8C5E                       := $8C5E;
