; ---------------------------------------------------------------------------
; MI library routines

race_name_table         := $7763;
r7911_table             := $7911;

w822C                   := $822C;
w822D                   := $822D;
w823B                   := $823B;
w823D                   := $823D;
w823F                   := $823F;
w8245                   := $8245;
w8247                   := $8247;
w824B                   := $824B;
w824D                   := $824D;
w8264                   := $8264;
w8265                   := $8265;

print_char              := $83D7;
cursor_to_col_1         := $83F6;
cursor_to_col_0         := $8411;
print_string_entry_x    := $8426
print_text_at_x_y       := $848A;
print_text              := $848E;
print_x_chars           := $84B9;
s84C0                   := $84C0;
s8689                   := $8689;
restore_text_area       := $8701;
store_text_area         := $870C;
s8772                   := $8772;
s8BA1  				    := $8BA1;

j8C5E                   := $8C5E;
