; ---------------------------------------------------------------------------
; ST library routines

CUR_X_OFF               := $2E; };
CUR_X_MAX               := $2F; };

CYR_Y_MIN               := $30; };
CUR_Y_MAX               := $31; };
CUR_X                   := $32; };
CUR_Y                   := $33; };

BM_ADDR_MASK            := $5C;
BM2_ADDR_MASK           := $5D;

init_snd_gfx            := $163A
s1649                   := $1649; };
fill_text_row           := $164F; };
set_text_window_full    := $1655; };
set_text_window_small   := $1658; };
swap_bitmaps            := $1664; };
draw_char               := $1667; };
buffer_input            := $1673; };
