; ---------------------------------------------------------------------------
; Kernel routines

KERNEL_LSTNSA   := $FF93
KERNEL_SCNKEY   := $FF9F
KERNEL_IECOUT   := $FFA8
KERNEL_UNLSTN   := $FFAE
KERNEL_LISTEN   := $FFB1
KERNEL_SETLFS   := $FFBA
KERNEL_SETNAM   := $FFBD
KERNEL_OPEN     := $FFC0
KERNEL_CLOSE    := $FFC3
KERNEL_CHKIN    := $FFC6
KERNEL_CLRCHN   := $FFCC
KERNEL_CHRIN    := $FFCF
KERNEL_LOAD     := $FFD5
KERNEL_SAVE     := $FFD8
KERNEL_GETIN    := $FFE4
